# Generated by Django 3.2.13 on 2022-07-01 08:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apiapp', '0003_accident_the_json'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='accident',
            name='the_json',
        ),
    ]
