# Generated by Django 3.2.13 on 2022-07-01 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apiapp', '0004_remove_accident_the_json'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accident',
            name='month',
            field=models.CharField(max_length=4, null=True),
        ),
        migrations.AlterField(
            model_name='accident',
            name='year',
            field=models.CharField(max_length=6, null=True),
        ),
    ]
